// Alert types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth types
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADED = 'USER_LOADED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Account types
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

// Search types
export const SUBMIT = 'SUBMIT';
export const FETCH_SEARCH_QUERY = 'FETCH_SEARCH_QUERY';
export const UPDATE_SEARCH_RESULTS = 'UPDATE_SEARCH_RESULTS';
export const UPDATE_CURRENT_RECIPE = 'UPDATE_CURRENT_RECIPE';
export const UPDATE_HISTORY_LIST = 'UPDATE_HISTORY_LIST';

export const NO_SEARCH_RESULTS = 'NO_SEARCH_RESULTS';

// Filter types
export const FETCH_FILTERS = 'FETCH_FILTERS';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const RESET_FILTERS = 'RESET_FILTERS';

// Query types
export const TEXT = 'TEXT';
export const INCLUDED_INGREDIENTS = 'INCLUDED_INGREDIENTS';
export const EXCLUDED_INGREDIENTS = 'EXCLUDED_INGREDIENTS';
export const CUISINES = 'CUISINES';
export const DISH_TYPES = 'DISH_TYPES';
export const DIETS = 'DIETS';
export const OCCASIONS = 'OCCASIONS';
export const HEALTHY = 'HEALTHY';
export const SUBMIT_SEARCH_QUERY = 'SUBMIT_SEARCH_QUERY';
export const RESET_SEARCH_QUERY = 'RESET_SEARCH_QUERY';

// export const PRICE_PER_SERVING = 'PRICE_PER_SERVING';
// export const READY_IN_MINUTES = 'READY_IN_MINUTES';

// Pager types
export const UPDATE_PAGER = 'UPDATE_PAGER';
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';
export const UPDATE_SORT_BY = 'UPDATE_SORT_BY';
export const UPDATE_ORDER_BY = 'UPDATE_ORDER_BY';

export const RESET_PAGER = 'RESET_PAGER';

// export const PAGES = 'PAGES';

<<<<<<< HEAD
// Recipe types
export const TITLE = 'TITLE';
export const SERVINGS = 'SERVINGS';
export const READY_IN_MINUTES = 'READY_IN_MINUTES';
export const VERY_HEALTHY = 'VERY_HEALTHY';
export const IMAGE = 'IMAGE';
export const IMAGE_URL = 'IMAGE_URL';
export const INGREDIENT_AMOUNT = 'INGREDIENT_AMOUNT';
export const INGREDIENT_UNIT = 'INGREDIENT_UNIT';
export const INGREDIENT_NAME = 'INGREDIENT_NAME';
export const EXTENDED_INGREDIENTS = 'EXTENDED_INGREDIENTS';
export const INGREDIENTS = 'INGREDIENTS';
export const ADD_INGREDIENTS = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENT';
export const INSTRUCTIONS = 'INSTRUCTIONS';
export const ADD_REMOVE_INSTRUCTIONS = 'ADD_REMOVE_INSTRUCTIONS';
// dishTypes, cuisines, occasions, diets already defined

export const RESET_RECIPE = 'RESET_RECIPE';

export const CREATE_RECIPE_SUCCESS = 'CREATE_RECIPE_SUCCES';
export const CREATE_RECIPE_FAIL = 'CREATE_RECIPE_FAIL';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
export const UPDATE_RECIPE_FAIL = 'UPDATE_RECIPE_FAIL';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAIL = 'DELETE_RECIPE_FAIL';

export const USER_RECIPES = 'USER_RECIPES';
export const USER_FAVORITES = 'USER_FAVORITES';
=======
// Carousel types
export const FETCH_CAROUSEL = 'FETCH_CAROUSEL';
export const UPDATE_CAROUSEL_QUERY = 'UPDATE_CAROUSEL_QUERY';
export const UPDATE_CAROUSEL_ITEMS = 'UPDATE_CAROUSEL_ITEMS';
export const UPDATE_CAROUSEL_PAGER = 'UPDATE_CAROUSEL_PAGER';
export const UPDATE_CAROUSEL_CURRENT_PAGE = 'UPDATE_CAROUSEL_CURRENT_PAGE';
export const NO_CAROUSEL_ITEMS = 'NO_CAROUSEL_ITEMS';
>>>>>>> 88e673ef39fc7717a6eb35976bc293a8049577f9
